#!/bin/bash
export GEM_HOME=$HOME/.gem
export PATH=$PATH:$GEM_HOME/bin
export PATH=$GEM_HOME/bin:$PATH
export PATH=$HOME/.gem/ruby/3.1.2/bin:$PATH

HOMEBREW_DIR=$(which brew)
eval "$($HOMEBREW_DIR shellenv)"

# rbenv global 3.1.2
eval "$(rbenv init - zsh)"
