require("user.plugins-setup") -- Keep at the top
require("user.core.options")
require("user.core.keymaps")
require("user.core.colorscheme")
require("user.plugins.comment")
require("user.plugins.nvim-tree")
require("user.plugins.lualine")
require("user.plugins.telescope")
require("user.plugins.nvim-cmp")
require("user.plugins.lsp.mason")
require("user.plugins.lsp.lsp-config")
require("user.plugins.lsp.null-ls")
require("user.plugins.autopairs")
require("user.plugins.treesitter")
require("user.plugins.gitsigns")
require("user.plugins.toggleterm")
require("user.plugins.which-key")
require("user.plugins.indent-blankline")
