# ---------- FYI ----------
#
# New Panes:
#
# leader ""     => horizontal
# leader %      => vertical
# leader c      => new nested window
#
# -------------------------

# Re-map prefix to ctrl + a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Reload tmux configuration with prefix + r
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Place status bar at the top of the window
set -g status-position top

# Enable mouse support
set -g mouse on

# Pane border appearance (tmux can't do gaps/rounded corners - text grid only)
set -g pane-border-lines heavy
set -g pane-border-style fg=#343f4c
set -g pane-active-border-style fg=#ffcc66

# Instruct the multiplexer to set the $TERM environment
# variable inside all its managed windows and panes.
# This acts as a critical signal informing CLI applications
# that the environment supports an expanded 256-color default-terminal
# rather than dropping back to basic 8-color compatibility.
set -g default-terminal "tmux-256color"

# Do not detach session when closing a window
set-option -g detach-on-destroy off

# Tell tmux to forward focus-gain and focus-loss escape sequences
# from the terminal emulator to the programs running
# inside the active tmux panes
set-option -g focus-events on

# Open a new pane in the same directory
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Vim style pane selection
# Prefix selection with the leader key
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Keep mouse selection highlighted and stay in copy mode
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-no-clear pbcopy
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear pbcopy

# ~~~~~ Plugins ~~~~~

# FYI: On new machines, you will need to install TPM (Tmux Plugin Manager) first.
# https://github.com/tmux-plugins/tpm

# Install plugins with prefix + I

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jaclu/tmux-menus' # Helper menu for shortcuts - prefix

# ~~~~~ Keep this at the bottom of the file ~~~~~
run '~/.tmux/plugins/tpm/tpm'
