#!/bin/bash

alias cl="clear"

# Node
alias node-version-name="node -pe process.release.lts"

# Git
# https://github.com/Everduin94/better-commits
alias commit="better-commits"
alias branch="better-branch"
alias my-prs="gh search prs --author=@me --state 'open'"
alias prs-to-review="gh search prs --review-requested=@me --state 'open'"
alias view-repo="gh repo view --web"
alias view-pr="gh pr view --web"
alias git-clean="git branch -vv | grep ': gone]' | grep -v '\*' | awk '{print $1}' | xargs -r git branch -D"

# Vim
alias nv="nvim"

# Tmux
alias tls="tmux ls"

# Other
alias timestamp="date +%s"
alias starwars="telnet towel.blinkenlights.nl"

alias mkd='dirFun() { mkdir -pv "$1"; cd "$1" }; dirFun '

alias random-password='openssl rand -base64 256 | tr -d '\n' | cut -c 1-256'

# Search files in current directory and open in selected editor
alias fd="fd-find"

alias ff="fzf --exclude node_modules --height 100% --layout reverse --info inline --border --preview 'batcat --color=always {}' --preview-window right,1,border-horizontal --bind 'ctrl-/:change-preview-window(50%|hidden|)' | xargs code -n ."

# Quickly serve the current directory as HTTP
alias serve='ruby -run -e httpd . -p 8000' # Or python -m SimpleHTTPServer

# Random
alias matrix="cmatrix"
# Toggle darkmode on/off (Mac)
alias darkmode="osascript -e 'tell app \"System Events\" to tell appearance preferences to set dark mode to not dark mode'"
alias restart="sudo shutdown -r now"
alias slack="export SLACK_DEVELOPER_MENU=true && open -a /Applications/Slack.app"
